services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    hostname: openldap
    ports: 
      - "389:389"
      - "636:636"
    volumes:
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
      - ./data_ldif/init.ldif:/tmp/init.ldif 
      #- ./data/slapd/ldif/init.ldif:/tmp/init.ldif 
   
    environment: 
      - LDAP_ORGANISATION=neurospinorg
      - LDAP_DOMAIN=neurospin.com
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin_pass
      - LDAP_CONFIG_PASSWORD=config_pass
      - "LDAP_BASE_DN=dc=neurospin,dc=com"
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=user-ro
      - LDAP_READONLY_USER_PASSWORD=ro_pass
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports: 
      - "80:80"
    environment: 
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap
  

  postgres:
    image: postgres:18
    container_name: postgres_db
    volumes:
      - postgres_data_poc:/var/lib/postgresql
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
  # backend:
  #   container_name: flask_backend
  #   build: ./backend
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - keycloak
  #     - postgres_api
  #   networks:
  #     - keycloak_network
  #     - app_network
  #   volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  # frontend:
  #   container_name: frontend
  #   build: ./front
  #   ports:
  #     - 5173:5173
   
  postgres_api:
    image: postgres:18
    container_name: postgres_api
    volumes:
      - postgres_data_api:/var/lib/postgresql
    env_file:
      - ./.env
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_api}
      - POSTGRES_USER=${POSTGRES_USER_api}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_api}
    networks:
      - app_network

volumes:
  postgres_data_poc:
  postgres_data_api:
    


networks:
  keycloak_network:
  openldap:
  app_network:
    
